### ISSUE TITLE
Break out K2 in separate repository

### ISSUE THREAD

**Issue by TimGremalm** [Zenterio/opensourcelib#2]
Please break out K2 in a separate repository, I find it hard to navigate.

**Comment by per-bohlin** [comment]
Sorry for the late reply, and thank you for your interest in K2.
Yes, it is in the works.
I'm working on a proper community edition to be released in a separate repository. Unfortunately I can't give you an estimated date. K2 depends on ZAF (another package in this repository) that need the same treatment. ZAF in turn depends on Znake (yet another package in this repository) that also needs its own repository.

**Comment by TimGremalm** [comment]
Yeah, I noticed all the dependencies :)
I'm looking forward for the community edition!
