### ISSUE TITLE
How to create out-of-tree/custom/local addons k2?

### ISSUE THREAD

**Issue by Risca** [Zenterio/opensourcelib#26]
I'm currenty working on an addon that I believe to be a very niche addon and that I don't really have any intention to try to get accepted upstream. I currently have this addon located in _k2/addons_ as untracked and an unstaged line in _requirements.txt_, but I would prefer to have it, e.g., in a separate repo.

How would I do this?

**Comment by per-bohlin** [comment]
When running k2, you can specify additional paths to plugins in your file system using the `--plugins-paths` or specified in any of the applicable k2 configuration files for the context where you want to use your plugin.
Example:
```shell
k2 --plugins-paths /path/to/my/special/plugin <command> <args>
```

The feature is used in many of the application system tests in the opensourcelib directory. grep for `plugins.paths` and you will find multiple examples.

If the answer fits your scenario, please close the issue.

**Comment by Risca** [comment]
Ah, totally missed that feature! I'll test it out and close this issue if it works to my liking =)

**Comment by Risca** [comment]
`--plugins-paths` works as intended. My only issue is that I usually run `zk2` using its venv (`source activate`), and when my own addon has requirements that are not part of the zk2 venv they won't find them. I either has to temporarily add those requirements to _k2/requirements.txt_ or (re-)install k2 on my system and setup a different venv (or don't use venv at all) for my own development. This is however not a K2 issue, but how I setup my venvs. The requirements for my own addons are not an issue for K2.

Closing.

**Comment by per-bohlin** [comment]
You are correct in that --plugins-paths only allow you to run "light-weight" plugins that doesn't have additional 3rd party dependencies beyond those already installed in the internal venv created by the make system.

If you want to install additional packages without modifying requirements.txt, such as a proper package with a setup.py as with addons in k2/addons, you can install them with `.venv/bin/pip install <path-to-package> or any regular pipy hosted package in similar way.

I will create an issue to create a "private.requirements.txt" that is automatically installed by the make venv target, included if it exists but not part of the repository; where private dependencies can be maintained without polluting the repository.
